from SCons.Environment import Environment
from SCons.Script import Return


Import('ENVIRONMENT')
ENVIRONMENT: Environment

env: Environment = ENVIRONMENT.Clone()
env.Append(
    CPPPATH = [
        env.Dir('.').srcnode(),
        env.Dir('#/src/library').srcnode(),
        env.Dir('#/thirdparty/doctest').srcnode()
    ]
)

Import('library')

objects = [
    *env.Glob('*.cpp'),
    library
]

tests = env.Program('test', objects)
Return('tests')